<a href="https://www.kaggle.com/code/vanshikaajindal/bert-lda?scriptVersionId=134868128" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import os
import shutil
!pip install tensorflow
import tensorflow as tf
!pip install tensorflow_text

import tensorflow_hub as hub
import tensorflow_text as text
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

data_folder = '/kaggle/input/text-summarization/data'

# Load train data
train_data = []
train_labels = []
class_names = []

train_folder = os.path.join(data_folder, 'train')
for class_folder in os.listdir(train_folder):
    if os.path.isdir(os.path.join(train_folder, class_folder)):
        class_names.append(class_folder)
        class_path = os.path.join(train_folder, class_folder)
        for file_name in os.listdir(class_path):
            if file_name.endswith('.txt'):
                file_path = os.path.join(class_path, file_name)
                with open(file_path, 'r') as file:
                    train_data.append(file.read())
                    train_labels.append(class_folder)

# Load test data
test_data = []
test_labels = []

test_folder = os.path.join(data_folder, 'test')
for class_folder in os.listdir(test_folder):
    if os.path.isdir(os.path.join(test_folder, class_folder)):
        class_path = os.path.join(test_folder, class_folder)
        for file_name in os.listdir(class_path):
            if file_name.endswith('.txt'):
                file_path = os.path.join(class_path, file_name)
                with open(file_path, 'r') as file:
                    test_data.append(file.read())
                    test_labels.append(class_folder)

/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tenso

In [2]:
import tensorflow as tf
import tensorflow_hub as hub
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import f1_score, precision_score
from sklearn.metrics import confusion_matrix

# Define BERT model
bert_model_name = 'small_bert/bert_en_uncased_L-4_H-512_A-8'
bert_model_path = '/kaggle/input/bert-model-1'  # Replace with the actual file path
bert_preprocess_model_path = '/kaggle/input/preocessor'  # Replace with the actual file path

# Load BERT model and preprocessing model
bert_preprocess_model = hub.KerasLayer(bert_preprocess_model_path)
bert_model = hub.KerasLayer(bert_model_path)

# Preprocess the data using BERT
train_preprocessed = bert_preprocess_model(train_data)
train_embeddings = bert_model(train_preprocessed)['pooled_output']

# Convert BERT embeddings to document-term matrix using CountVectorizer
vectorizer = CountVectorizer()
train_doc_term_matrix = vectorizer.fit_transform(train_data)


In [3]:
# Apply LDA for dimensionality reduction
lda = LatentDirichletAllocation(n_components=10)  # Adjust the number of components as needed
train_lda_features = lda.fit_transform(train_doc_term_matrix)

# Convert labels to numeric format
label_encoder = LabelEncoder()
train_labels_encoded = label_encoder.fit_transform(train_labels)
test_labels_encoded = label_encoder.transform(test_labels)

# Train a classifier on LDA features
classifier = tf.keras.Sequential([
    tf.keras.layers.Dense(256, activation='relu', input_shape=(train_lda_features.shape[1],)),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(len(class_names), activation='softmax')
])

classifier.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
classifier.fit(train_lda_features, train_labels_encoded, epochs=10)

# Preprocess and classify test data
test_preprocessed = bert_preprocess_model(test_data)
test_embeddings = bert_model(test_preprocessed)['pooled_output']
test_doc_term_matrix = vectorizer.transform(test_data)
test_lda_features = lda.transform(test_doc_term_matrix)
predictions = classifier.predict(test_lda_features)



Epoch 1/10
233/233 [==============================] - 2s 3ms/step - loss: 1.2140 - accuracy: 0.5314
Epoch 2/10
233/233 [==============================] - 1s 3ms/step - loss: 1.1056 - accuracy: 0.5738
Epoch 3/10
233/233 [==============================] - 1s 3ms/step - loss: 1.0829 - accuracy: 0.5827
Epoch 4/10
233/233 [==============================] - 1s 3ms/step - loss: 1.0757 - accuracy: 0.5848
Epoch 5/10
233/233 [==============================] - 1s 3ms/step - loss: 1.0727 - accuracy: 0.5832
Epoch 6/10
233/233 [==============================] - 1s 3ms/step - loss: 1.0627 - accuracy: 0.5862
Epoch 7/10
233/233 [==============================] - 1s 3ms/step - loss: 1.0606 - accuracy: 0.5929
Epoch 8/10
233/233 [==============================] - 1s 3ms/step - loss: 1.0573 - accuracy: 0.5936
Epoch 9/10
233/233 [==============================] - 1s 3ms/step - loss: 1.0564 - accuracy: 0.5926
Epoch 10/10
63/63 [==============================] - 0s 1ms/step


In [4]:
# # Convert predictions back to labels
# predicted_labels_encoded = tf.argmax(predictions, axis=1)
# predicted_labels = label_encoder.inverse_transform(predicted_labels_encoded.numpy())
# # Convert labels to numeric format
# label_encoder = LabelEncoder()
# train_labels_encoded = label_encoder.fit_transform(train_labels)
# test_labels_encoded = label_encoder.transform(test_labels)

# # Create and fit the OneHotEncoder
# one_hot_encoder = OneHotEncoder()
# one_hot_encoder.fit(train_labels_encoded.reshape(-1, 1))

# # Convert labels to one-hot encoded format
# train_labels_one_hot = one_hot_encoder.transform(train_labels_encoded.reshape(-1, 1)).astype(float)
# test_labels_one_hot = one_hot_encoder.transform(test_labels_encoded.reshape(-1, 1)).astype(float)

# # Train a classifier on LDA features
# classifier = Pipeline([
#     ('classifier', tf.keras.Sequential([
#         tf.keras.layers.Dense(256, activation='relu'),
#         tf.keras.layers.Dense(len(class_names), activation='softmax')
#     ]))
# ])

# classifier['classifier'].compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
# classifier.fit(train_lda_features, tf.keras.utils.to_categorical(train_labels_encoded))

# # Preprocess and classify test data
# test_preprocessed = bert_preprocess_model(test_data)
# test_embeddings = bert_model(test_preprocessed)['pooled_output']
# test_doc_term_matrix = vectorizer.transform(test_data)
# test_lda_features = lda.transform(test_doc_term_matrix)
# predictions = classifier.predict(test_lda_features)

# # Convert predictions back to labels
# predicted_labels_encoded = tf.argmax(predictions, axis=1)
# predicted_labels = label_encoder.inverse_transform(predicted_labels_encoded.numpy())

# # Convert labels to numeric format
# test_labels_encoded = label_encoder.transform(test_labels)

# # Evaluate the classifier
# accuracy = tf.metrics.Accuracy()
# accuracy.update_state(test_labels_encoded, predicted_labels_encoded)
# loss = classifier['classifier'].evaluate(test_lda_features, tf.keras.utils.to_categorical(test_labels_encoded), verbose=0)[0]
# f1 = f1_score(test_labels, predicted_labels, average='weighted')
# precision = precision_score(test_labels, predicted_labels, average='weighted')
# confusion = confusion_matrix(test_labels, predicted_labels)

# print('Accuracy:', accuracy.result().numpy())
# print('Loss:', loss)
# print('F1 Score:', f1)
# print('Precision:', precision)
# print(confusion)

# Convert predictions back to labels
predicted_labels_encoded = tf.argmax(predictions, axis=1)
predicted_labels = label_encoder.inverse_transform(predicted_labels_encoded.numpy())

# Evaluate the classifier
accuracy = tf.metrics.Accuracy()
accuracy.update_state(test_labels_encoded, predicted_labels_encoded)
loss = classifier.evaluate(test_lda_features, test_labels_encoded, verbose=0)[0]
f1 = f1_score(test_labels, predicted_labels, average='weighted')
precision = precision_score(test_labels, predicted_labels, average='weighted')
confusion = confusion_matrix(test_labels, predicted_labels)

print('Accuracy:', accuracy.result().numpy())
print('Loss:', loss)
print('F1 Score:', f1)
print('Precision:', precision)
print(confusion)


Accuracy: 0.65184814
Loss: 0.9629627466201782
F1 Score: 0.6038137593987941
Precision: 0.6534223629222925
[[ 12  36  34 147   1]
 [  1 259  10 196  11]
 [  0  13  95 148   1]
 [  5  43  18 915   1]
 [  0  25   1   6  24]]


In [5]:

# True Positives (TP)
tp = confusion.diagonal()

# False Positives (FP)
fp = confusion.sum(axis=0) - tp

# True Negatives (TN)
tn = confusion.sum() - (tp + fp + confusion.diagonal())

# False Negatives (FN)
fn = confusion.sum(axis=1) - tp

print('True Positives:', tp)
print('False Positives:', fp)
print('True Negatives:', tn)
print('False Negatives:', fn)

True Positives: [ 12 259  95 915  24]
False Positives: [  6 117  63 497  14]
True Negatives: [1972 1367 1749 -325 1940]
False Negatives: [218 218 162  67  32]


In [6]:
import os
import shutil
!pip install tensorflow
import tensorflow as tf
!pip install tensorflow_text

import tensorflow_hub as hub
import tensorflow_text as text
from sklearn.decomposition import NMF
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder

# Example usage
data_folder = '/kaggle/input/text-summarization/data'

# Load train data
train_data = []
train_labels = []
class_names = []

train_folder = os.path.join(data_folder, 'train')
for class_folder in os.listdir(train_folder):
    if os.path.isdir(os.path.join(train_folder, class_folder)):
        class_names.append(class_folder)
        class_path = os.path.join(train_folder, class_folder)
        for file_name in os.listdir(class_path):
            if file_name.endswith('.txt'):
                file_path = os.path.join(class_path, file_name)
                with open(file_path, 'r') as file:
                    train_data.append(file.read())
                    train_labels.append(class_folder)

# Load test data
test_data = []
test_labels = []

test_folder = os.path.join(data_folder, 'test')
for class_folder in os.listdir(test_folder):
    if os.path.isdir(os.path.join(test_folder, class_folder)):
        class_path = os.path.join(test_folder, class_folder)
        for file_name in os.listdir(class_path):
            if file_name.endswith('.txt'):
                file_path = os.path.join(class_path, file_name)
                with open(file_path, 'r') as file:
                    test_data.append(file.read())
                    test_labels.append(class_folder)

import tensorflow as tf
import tensorflow_hub as hub
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import f1_score, precision_score
from sklearn.metrics import confusion_matrix

# Define BERT model
bert_model_name = 'small_bert/bert_en_uncased_L-4_H-512_A-8'
bert_model_path = '/kaggle/input/bert-model-1'  # Replace with the actual file path
bert_preprocess_model_path = '/kaggle/input/preocessor'  # Replace with the actual file path

# Load BERT model and preprocessing model
bert_preprocess_model = hub.KerasLayer(bert_preprocess_model_path)
bert_model = hub.KerasLayer(bert_model_path)

# Preprocess the data using BERT
train_preprocessed = bert_preprocess_model(train_data)
train_embeddings = bert_model(train_preprocessed)['pooled_output']

# Convert BERT embeddings to document-term matrix using CountVectorizer
vectorizer = CountVectorizer()
train_doc_term_matrix = vectorizer.fit_transform(train_data)

# Apply NMF for dimensionality reduction
nmf = NMF(n_components=10, random_state=42)  # Adjust the number of components as needed
train_nmf_features = nmf.fit_transform(train_doc_term_matrix)

# Convert labels to numeric format
label_encoder = LabelEncoder()
train_labels_encoded = label_encoder.fit_transform(train_labels)
test_labels_encoded = label_encoder.transform(test_labels)

# Train a classifier on BERT + NMF features
classifier = tf.keras.Sequential([
    tf.keras.layers.Dense(256, activation='relu', input_shape=(train_nmf_features.shape[1],)),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(len(class_names), activation='softmax')
])

classifier.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
classifier.fit(train_nmf_features, train_labels_encoded, epochs=10)

# Preprocess and classify test data
test_preprocessed = bert_preprocess_model(test_data)
test_embeddings = bert_model(test_preprocessed)['pooled_output']
test_doc_term_matrix = vectorizer.transform(test_data)
test_nmf_features = nmf.transform(test_doc_term_matrix)
predictions = classifier.predict(test_nmf_features)

# Convert predictions back to labels
predicted_labels_encoded = tf.argmax(predictions, axis=1)
predicted_labels = label_encoder.inverse_transform(predicted_labels_encoded.numpy())

# Evaluate the classifier
accuracy = tf.metrics.Accuracy()
accuracy.update_state(test_labels_encoded, predicted_labels_encoded)
loss = classifier.evaluate(test_nmf_features, test_labels_encoded, verbose=0)[0]
f1 = f1_score(test_labels, predicted_labels, average='weighted')
precision = precision_score(test_labels, predicted_labels, average='weighted')
confusion = confusion_matrix(test_labels, predicted_labels)

print('Accuracy:', accuracy.result().numpy())
print('Loss:', loss)
print('F1 Score:', f1)
print('Precision:', precision)
print(confusion)



/opt/conda/lib/python3.10/site-packages/sklearn/decomposition/_nmf.py:1665: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(


Epoch 1/10
233/233 [==============================] - 2s 3ms/step - loss: 1.0801 - accuracy: 0.5763
Epoch 2/10
233/233 [==============================] - 1s 3ms/step - loss: 0.8230 - accuracy: 0.6778
Epoch 3/10
233/233 [==============================] - 1s 3ms/step - loss: 0.7850 - accuracy: 0.6956
Epoch 4/10
233/233 [==============================] - 1s 3ms/step - loss: 0.7710 - accuracy: 0.7048
Epoch 5/10
233/233 [==============================] - 1s 3ms/step - loss: 0.7566 - accuracy: 0.7092
Epoch 6/10
233/233 [==============================] - 1s 3ms/step - loss: 0.7478 - accuracy: 0.7173
Epoch 7/10
233/233 [==============================] - 1s 3ms/step - loss: 0.7425 - accuracy: 0.7198
Epoch 8/10
233/233 [==============================] - 1s 3ms/step - loss: 0.7410 - accuracy: 0.7169
Epoch 9/10
233/233 [==============================] - 1s 3ms/step - loss: 0.7320 - accuracy: 0.7211
Epoch 10/10
63/63 [==============================] - 0s 1ms/step
Accuracy: 0.7062937
Loss: 0.7089475